name: Deployment Exercise 2
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps: 
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "thao1" > test.txt
      - name: Lint
        run: cat test.txt
      - name: Deploy code
        run: ls -l