name: test

on:
  push:
    branches:
      - "master"
      - "github-test"
jobs:
  job1:
    runs-on: self-hosted
    steps:
      - name: job1
        run: echo "job1"

  job2:
    if: ${{ github.ref == 'refs/heads/github-test' }}
    runs-on: self-hosted
    steps:
      - name: job2
        run: echo "job2"

  job3:
    runs-on: self-hosted
    needs: job2
    steps:
      - name: job3
        run: echo "job3"