name: Call reusable workflow

on:
  push:

env:
  BUILD_LINK: https://xxxxx

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: test
        run: pwd
  slack-notification:
    name: Slack notification
    needs: build
    uses: ./.github/workflows/reuse.yaml
    with:
      message: $BUILD_LINK \nhello
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}