name: Deployment Exercise 1 (master)
on: push
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check aws cli
        run: aws --version
      - name: Check docker
        run: docker -v
