name: Deployment Exercise 1 (master)
on: push
jobs:
  deploy:
    runs-on: cicd-t
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: touch test.txt
      - name: Deploy code
        run: echo "Deploying.qestq.master 2"
