name: Call reusable workflow

on:
  push:

env:
  BUILD_LINK: https://xxxxx

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: test
        run: pwd
  slack-notification:
    if: ${{ env.BUILD_LINK == 'abc' }}
    name: Slack notification
    needs: build
    uses: ./.github/workflows/reuse.yaml
    with:
      message: 'aaaaa'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}