name: Call reusable workflow

on:
  push:

env:
  BUILD_LINK: https://xxxxxxz

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: test
        run: 'echo ${{ env.BUILD_LINK }} '
  slack-notification:
    name: Slack notification
    needs: build
    uses: ./.github/workflows/reuse.yaml
    with:
      message: 'aaaaaa'
      text: '["hello","world"]'
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}