name: Call reusable workflow

on:
  push:
    branches:
      - "master"

env:
  BUILD_LINK: https://xxxxxxz

jobs:
  slack-notification:
    name: Slack notification
    env:
      sha: ${GITHUB_SHA:0:8}
    uses: ./.github/workflows/reuse.yaml
    with:
      message: '${{ env.sha }}'
      text: 'hello,world'
      command: |
         echo "hello"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}