name: Call reusable workflow

on:
  push:
    branches:
      - "dev01/cs"

env:
  BUILD_LINK: https://xxxxxxz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: test
        env:
          GR: ${{ github.ref }}
        run: |
          arr=(${GR//// })
          echo ${arr[0]}
          echo ${arr[1]}
          echo ${arr[2]}
          echo ${arr[*]} 
          echo ${{ env.BUILD_LINK }}
          echo ${{ github.action_status }}
  