name: Call reusable workflow

on:
  push:

env:
  BUILD_LINK: https://xxxxxxz

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: test
        run: 'echo ${{ env.BUILD_LINK }} '
  slack-notification:
    name: Slack notification
    needs: build
    uses: ./.github/workflows/reuse.yaml
    with:
      message: |-
         ${{ needs.build.result  == 'success' 
        && ${{ github.run_id }}
        || '${{ github.run_id }}' }}
      text: 'hello,world'
      command: |
         echo "hello"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}