name: Call reusable workflow

on:
  push:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reuse.yaml
    with:
      runner: self-hosted

  finish:
    run: echo "Call reusable workflow"