name: Call reusable workflow

on:
  push:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: test
        run: pwd
  slack-notification:
    name: Slack notification
    needs: build
    uses: ./.github/workflows/reuse.yaml
    with:
      message: |
        ${{ needs.build.result == 'success'
        && 'succe\nss'
        || 'failure' }}
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}