name: Call reusable workflow

on:
  push:
    branches:
      - "dev01/cs"

env:
  BUILD_LINK: https://xxxxxxz

jobs:
  build:
    runs-on: self-hosted
    steps:
      - id: test
        env:
          GR: ${{ github.ref }}
        run: |
          arr = (${GR////})
          echo ${ arr[0] }
          echo ${ arr[1] }
          echo ${ arr[2] }
         echo ${ arr } 
          echo ${{ env.BUILD_LINK }}
          echo ${{ github.action_status }}
  slack-notification:
    if: false
    name: Slack notification
    needs: build
    uses: ./.github/workflows/reuse.yaml
    with:
      message: |-
         ${{ (needs.build.result == 'success' && needs.build.result == 'failed') && format('aaabbbbbba={0}', github.run_id) || 'failure' }}
      text: 'hello,world'
      command: |
         echo "hello"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}
  test-github-action-status:
    if: ${{ always() && !failure()}}
    runs-on: self-hosted
    needs: slack-notification
    steps:
      - name: test
        run: |
          echo ${{ github.action_status }}

  test-github-action-status_2:
    if: ${{ always() && failure()}}
    runs-on: self-hosted
    needs: slack-notification
    steps:
      - name: test
        run: |
          echo ${{ github.action_status }}
    
