name: Deployment Exercise 1 (master)
on: push
jobs:
  deploy:
    runs-on: cicd-t
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy code
        run: echo "Deploying.qestq.master 2"
