name: Call reusable workflow

on:
  push:

jobs:
  slack-notification:
    name: Slack notification
    runs-on: self-hosted
    steps:
      - name: Slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          payload: |
            {
              "text": "GitHub Action build result"
            }
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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