name: Call reusable workflow

on:
  push:

jobs:
  slack-notification:
    name: Slack notification
    uses: ./.github/workflows/reuse.yaml
    with:
      message: 'hello'
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}