name: Call reusable workflow

on:
  push:

env:
  BUILD_LINK: https://xxxxxxz

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Test
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: aa.json
      - id: test
        run: 'echo ${{ env.BUILD_LINK }} '
  slack-notification:
    name: Slack notification
    needs: build
    uses: ./.github/workflows/reuse.yaml
    with:
      message: |-
         ${{ needs.build.result == 'success' && format('aaaa={0}', github.run_id) || 'failure' }}
      text: 'hello,world'
      command: |
         echo "hello"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}