name: Call reusable workflow

on:
  push:

env:
  BUILD_LINK: https://xxxxxxz

jobs:
  build:
    runs-on: self-hosted
    steps:
      - id: test
        run: |
          echo ${{ env.BUILD_LINK }}
          echo ${{ github.action_status }}
  slack-notification:
    if: false
    name: Slack notification
    needs: build
    uses: ./.github/workflows/reuse.yaml
    with:
      message: |-
         ${{ (needs.build.result == 'success' && needs.build.result == 'failed') && format('aaaa={0}', github.run_id) || 'failure' }}
      text: 'hello,world'
      command: |
         echo "hello"
    secrets:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_BOT_TOKEN }}
  test-github-action-status:
    if: ${{ always() && success()}}
    runs-on: self-hosted
    needs: slack-notification
    steps:
      - name: test
        run: |
          echo ${{ github.action_status }}
    
