name: notification 

on:
  workflow_call:
    inputs:
      message:
        description: "self"
        required: true
        type: string
      text:
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
jobs:
  slack:
    name: Slack
    runs-on: self-hosted
    steps:
      - name: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: '{ "text": "${{ inputs.message }}" }'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: test json
        run: |
           echo '${{ inputs.text }}' | jq -r '.[0]'
     