name: notification 

on:
  workflow_call:
    inputs:
      message:
        description: "self"
        required: true
        type: string
      text:
        type: string
      command:
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        required: true
jobs:
  slack:
    name: Slack
    runs-on: self-hosted
    outputs:
      msg: ${{ steps.prepare.outputs.msg }}
    steps:
      - name: prepare msg
        id: prepare
        run: |
          echo "msg="${{ inputs.message }} | sed -e ':a;N;$!ba;s/\n/ /g'
      - name: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          payload: '{ "text": "${{ inputs.message }}" }'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: test json
        run: |
           readarray -d , -t tags <<< ${{ inputs.text }}
           echo ${tags[0]}
      - name: test command
        run: |
           ${{ inputs.command }}
     