name: Test for reusable workflow

on:
  workflow_call:
    inputs:
      runner:
        description: self-hosted runn
        required: true
        type: string
jobs:
  build:
    name: build 
    runs-on: ${{ inputs.runner }}
    steps:
      - name: First step
        run: echo "Hello world"
